version: "3.8"
services:

  flask-example:
    build:
      context: .
    container_name: flask-example
    image: flask-example:latest
    depends_on:
      - mongodb_container
    ports:
      - "5000:5000"
    hostname: flask-example
    networks:
      - default
      - db_network
    volumes:
    - source: ./05-structure
      target: /home/webserver/
      type: bind
    command: python3 manage.py runserver

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - default
      - db_network
#    ports:
#      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  db_network:
    name: db_network
